# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
np.random.random((3,1))

array([[0.77682341],
       [0.14134518],
       [0.70746311]])

In [3]:
tf.__version__

'2.13.0-rc2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()
# This line creates a new instance of a Sequential model and assigns it to the variable ann.
# The Sequential model is a linear stack of layers, where you can add layers one by one.


### Adding the input layer and the first hidden layer

- tf.keras.layers.Dense: This is a class from the Keras API that represents a fully connected (dense) layer in a neural network.

- units=6: This parameter specifies the number of neurons (or units) in the Dense layer. In this case, the layer will have 6 neurons.

- activation='relu': This parameter specifies the activation function to be used in the Dense layer. 'relu' stands for Rectified Linear Unit, which is a commonly used activation function in deep learning. It introduces non-linearity to the model.

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

Binary crossentropy, or binary_crossentropy, is a commonly used loss function in binary classification problems. It is specifically designed for models that predict probabilities for two classes. 


In binary classification, each input is assigned to one of two classes, often represented as class 0 and class 1. The binary crossentropy loss measures the dissimilarity between the predicted probabilities and the true labels. It quantifies how well the predicted probabilities match the actual labels.


Mathematically, the binary crossentropy loss is computed as follows:

```
binary_crossentropy(y_true, y_pred) = - (y_true * log(y_pred) + (1 - y_true) * log(1 - y_pred))
```

where:
- `y_true` is the true label (either 0 or 1).
- `y_pred` is the predicted probability of the positive class (between 0 and 1).


The binary crossentropy loss encourages the model to assign high probabilities to the correct class and low probabilities to the incorrect class. It penalizes larger errors more strongly, and its value decreases as the predicted probabilities align better with the true labels.


During the training process, the model seeks to minimize the binary crossentropy loss by adjusting its internal parameters. This helps the model learn the patterns in the data and make more accurate predictions for binary classification tasks.

The key idea behind Adam is to update the learning rates of the parameters differently based on their importance. Parameters that receive larger gradients will have their learning rates adjusted more aggressively, while parameters that receive smaller gradients will have their learning rates adjusted more conservatively. This adaptive learning rate scheme helps the optimizer converge faster and more reliably.



### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 513us/step - loss: 0.5669 - accuracy: 0.7535
Epoch 2/100
250/250 [==============================] - 0s 343us/step - loss: 0.4868 - accuracy: 0.7959
Epoch 3/100
250/250 [==============================] - 0s 337us/step - loss: 0.4485 - accuracy: 0.8050
Epoch 4/100
250/250 [==============================] - 0s 357us/step - loss: 0.4288 - accuracy: 0.8126
Epoch 5/100
250/250 [==============================] - 0s 331us/step - loss: 0.4204 - accuracy: 0.8194
Epoch 6/100
250/250 [==============================] - 0s 321us/step - loss: 0.4157 - accuracy: 0.8226
Epoch 7/100
250/250 [==============================] - 0s 318us/step - loss: 0.4130 - accuracy: 0.8239
Epoch 8/100
250/250 [==============================] - 0s 326us/step - loss: 0.4102 - accuracy: 0.8240
Epoch 9/100
250/250 [==============================] - 0s 327us/step - loss: 0.4085 - accuracy: 0.8267
Epoch 10/100
250/250 [==============================] - 0s 320us/step - l

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [20]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 12ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 200  205]]


0.8605